#!/bin/bash

# Set it up to use the locally installed Perl 5.16.0
export PATH=${HOME}/perl5/perlbrew/perls/perl-5.16.3/bin:$PATH
PERL_CPANM_OPT="--local-lib=/$HOME/perl5"
source ~/perl5/perlbrew/etc/bashrc

export PERL5LIB=${HOME}/webapp/lib

cd ~/webapp

pwd
id
env

plackup --server Starman --env development \
	--listen 127.0.0.1:6000 --workers 2 --preload-app \
        --user cewebapp --group cewebapp \
        --app ./app.psgi --pid ~/var/webapp.pid --daemonize \
	--access-log ~/log/webapp.log 2>&1
